BookCatalog/Models/DataTablePaginationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookCatalog.Models
{
    public class DataTablePaginationModel
    {
        public string sEcho { get; set; }
        public int iDisplayLength { get; set; }
        public int iDisplayStart { get; set; }
        public string iSortCol_0 { get; set; }
        public string sSortDir_0 { get; set; }
        public string sSearch_2 { get; set; }
    }
}

BookCatalog/Models/Enums/BookOrderType.cs
namespace BookCatalog.Models.Enums
{
    public enum BookOrderType
    {
        Id = 0,
        PublishingYear = 3,
        PagesAmount = 4,
        Rate = 5
    }
}

BookCatalog/Models/ServiceResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookCatalog.Models
{
    public class ServiceResponse
    {
        public bool IsSuccessfull { get; set; }
        public string ResultMessage { get; set; }
    }
}

BookCatalog/ViewModels/AuthorSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookCatalog.ViewModels
{
    public class AuthorSearchViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AmountOfBooks { get; set; }
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
    }
}

BookCatalog/ViewModels/AuthorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookCatalog.ViewModels
{
    public class AuthorViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "First Name is required field")]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required field")]
        [MaxLength(100)]
        public string LastName { get; set; }
    }
}

BookCatalog/ViewModels/BookSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Script.Serialization;
using BookCatalog.Data.Entities;

namespace BookCatalog.ViewModels
{
    public class BookSearchViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int PublishingYear { get; set; }
        public int PagesAmount { get; set; }
        public int Rate { get; set; }
        public string Authors
        {
            get
            {
                var authors = string.Empty;
                if (AuthorsCollection.Count > 0)
                {
                    AuthorsCollection.ForEach(e => authors += string.IsNullOrEmpty(authors) 
                    ? e.FirstName + " " + e.LastName
                    : ", " + e.FirstName + " " + e.LastName);
                }
                return authors;
            }
        }

        [ScriptIgnore]
        public List<Author> AuthorsCollection { get; set; }
    }
}

BookCatalog/ViewModels/BookViewModel.cs
using BookCatalog.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BookCatalog.ViewModels
{
    public class BookViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Book's Title is required field")]
        [MaxLength(100)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Year of Publishing is required field")]
        public DateTime PublishingYear { get; set; }

        [Required(ErrorMessage = "Amount of Pages is required field")]
        public int PagesAmount { get; set; }

        [Required(ErrorMessage = "Book's Rate is required field (from 1 to 5)")]
        [Range(1, 5)]
        public int Rate { get; set; }

        [Required(ErrorMessage ="At least one author should be selected")]
        public int[] Authors { get; set; }

        public virtual ICollection<Author> AuthorsCollection { get; set; }
    }
}

BookCatalog/Controllers/BookController.cs
using BookCatalog.Models;
using BookCatalog.Services.Interfaces;
using BookCatalog.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace BookCatalog.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetBookResultTable(DataTablePaginationModel paginationModel)
        { 
            return Json(new
            {
                sEcho = paginationModel.sEcho,
                iTotalDisplayRecords = bookService.GetTotalBooksAmount(paginationModel.sSearch_2),
                aaData = bookService.GetFilteredBooks(paginationModel)
            });
        }

        [HttpPost]
        public JsonResult SaveBook(BookViewModel bookViewModel)
        {
            if (!ModelState.IsValid)
            {
                return Json( new { result = new ServiceResponse() { IsSuccessfull = false, ResultMessage = ModelState.FirstOrDefault(m => m.Value.Errors.Any()).Value.Errors.FirstOrDefault().ErrorMessage } });
            }
            return Json(new { result = bookService.SaveBook(bookViewModel) });
        }

        [HttpPost]
        public JsonResult RemoveBook(int? bookId)
        {
            return Json(new { result = bookService.RemoveBook(bookId) });
        }

        [HttpPost]
        public JsonResult SaveAuthor(AuthorViewModel authorViewModel)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { result = new ServiceResponse() { IsSuccessfull = false, ResultMessage = ModelState.FirstOrDefault(m => m.Value.Errors.Any()).Value.Errors.FirstOrDefault().ErrorMessage } });
            }
            return Json( new { result = bookService.SaveAuthor(authorViewModel)});
        }

        [HttpGet]
        public JsonResult GetAuthorsList()
        {
            return Json(new
            {
                authors = bookService.GetAuthorsList(),

            }, JsonRequestBehavior.AllowGet);
        }
    }
}

BookCatalog/Controllers/HomeController.cs
using BookCatalog.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookCatalog.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BookCatalog/Views/Book/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    var bookCatalogTable = "BookCatalogTable";
}
<style>
    td.details-control {
        text-align: center;
        color: forestgreen;
        cursor: pointer;
        font-size: x-large;
    }

    tr.shown td.details-control {
        text-align: center;
        color: red;
        font-size: x-large;
    }

    td.edit-control {
        color: forestgreen;
        font-size: x-large;
        text-align: center;
        cursor: pointer;
    }

    td.remove-control {
        color: red;
        font-size: x-large;
        text-align: center;
        cursor: pointer;
    }

    i.edit-author-control {
        color: forestgreen;
        font-size: x-large;
        text-align: center;
        cursor: pointer;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <button class="btn btn-success col-md-12" id="newBookBtn">New book</button>
        </div>
        <div class="col-md-6"></div>
        <div class="col-md-3">
            <button class="btn btn-primary col-md-12" id="newAuthorBtn">New author</button>
        </div>
    </div>
</div>
<div id="editBookDialog" title="Create Book"></div>
<div id="editAuthorDialog" title="Create Author"></div>

<div class="row" style="margin-top: 20px">
    <div class="col-md-12">
        <div class="container">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="form-horizontal clearfix">
                        @Html.Partial("_BookCatalogTable", bookCatalogTable)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        bookCatalog.setUrlForTable({
            getBookResultTable: "@Url.Action("GetBookResultTable", "Book")",
            getAuthorsList: "@Url.Action("GetAuthorsList", "Book")",
            updateBook: "@Url.Action("SaveBook", "Book")",
            updateAuthor: "@Url.Action("SaveAuthor", "Book")",
            removeBook: "@Url.Action("RemoveBook", "Book")"
        });
        bookCatalog.InitBookTable();
        bookCatalog.InitEditBookModal();
        bookCatalog.InitEditAuthorModal();
        bookCatalog.getAuthorsList();
    });
</script>

BookCatalog/Views/Book/_BookCatalogTable.cshtml
@model string
<table id="@Model" class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Book#</th>
            <th>Title</th>
            <th>Published</th>
            <th>Pages</th>
            <th>Rate</th>
            <th>Author(s)</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
</table>

BookCatalog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookCatalog/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookCatalog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BookCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Catalog</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/dataTables")
    @Styles.Render("~/Content/font-awesome")
    @Styles.Render("~/Content/chosen")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/chosen")
    @Scripts.Render("~/bundles/application")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Book", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Catalog</p>
        </footer>
    </div>


</body>
</html>